src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GameRepository::class)]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 30, unique:true)]
    private $title;

    #[ORM\Column(type: 'integer')]
    private $min_players;

    #[ORM\Column(type: 'integer')]
    private $max_players;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Contest::class, orphanRemoval: true)]
    private $contests;

    public function __construct()
    {
        $this->contests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMinPlayers(): ?int
    {
        return $this->min_players;
    }

    public function setMinPlayers(int $min_players): self
    {
        $this->min_players = $min_players;

        return $this;
    }

    public function getMaxPlayers(): ?int
    {
        return $this->max_players;
    }

    public function setMaxPlayers(int $max_players): self
    {
        $this->max_players = $max_players;

        return $this;
    }

    /**
     * @return Collection<int, Contest>
     */
    public function getContests(): Collection
    {
        return $this->contests;
    }

    public function addContest(Contest $contest): self
    {
        if (!$this->contests->contains($contest)) {
            $this->contests[] = $contest;
            $contest->setGame($this);
        }

        return $this;
    }

    public function removeContest(Contest $contest): self
    {
        if ($this->contests->removeElement($contest)) {
       
            if ($contest->getGame() === $this) {
                $contest->setGame(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\GameRepository;
use App\Repository\PlayerRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Game;
use App\Entity\Contest;
use App\Form\CommencerPartieType;

class HomeController extends AbstractController
{
    
    #[Route('/', name: 'app_home')]
    public function displayGame(GameRepository $gameRepository, PlayerRepository $playerRepository): Response
    {
        return $this->render('home/index.html.twig', [
            'games' => $gameRepository->findAll(),
            'nb_players' => count($playerRepository->findAll()),
            'winners' => $playerRepository->findWinners()
        ]);
    }

    #[Route('/commencer-une-partie-{title}', name: 'app_home_contest')]
    public function commencer(Game $jeu, EntityManagerInterface $em, Request $rq)
    {
      $partie = new Contest;
      $partie->setGame($jeu);
      $form = $this->createForm(CommencerPartieType::class, $partie);
      $form->handleRequest($rq);
      if($form->isSubmitted() && $form->isValid()){
        $em->persist($partie);
        $em->flush();
        $this->addFlash("success", "La nouvelle partie a bien été enregistrée");
        return $this->redirectToRoute("app_home");
      }
      return $this->render("home\commencer.html.twig", [
          "form" => $form->createView()
      ]);
    }
}

templates/home/commencer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Partie{% endblock %}

{% block body %}
    {# def. des variables dans twig #}
    {% set contest = form.vars.value %}
    <h2>Commencer une nouvelle partie de {{contest.game.title}} :</h2>
    {# {{ form(form) }} #}
    {{ form_start(form) }} 
        {{ form_row(form.players) }}
        <div class="row">
            <div class="col-3">{{ form_label(form.start_date) }}</div>
            <div class="col-9">{{ form_widget(form.start_date, {attr: {class: 'text-primary'}}) }}</div>
        </div>
        {{ form_errors(form.start_date) }}
        {{ form_help(form.start_date) }}
    
        <button class="btn btn-secondary">Commencer la partie</button>
    {{ form_end(form) }}
{% endblock %}

{% block footer %}{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MyScoreboard{% endblock %}

{% block body %}
    
    <div class="card-columns">
    {% for game in games %}
    {#
    <div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">{{game.title}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">nombre de parties jouées : {{ game.contests|length }}</h6>
        <p class="card-text">
            Entre {{game.minPlayers}} et {{game.maxPlayers}} joueurs
        </p>
        <p><u><strong>Ils ont déjà joué :</u></strong>
            {% for partieItem in game.contests %}
                {% for joueurItem in partieItem.players %}
                    {{ joueurItem.nickname }}, 
                {% endfor %}
            {% endfor %}
        </p>
        <a href="{{ path('app_home_contest', {title: game.title}) }}" class="card-link">Commencer une partie</a>
    </div>
    </div>
    #}
   {{ include("admin/game/_card.html.twig") }}
    {% else %}
        <mark>Aucun resutat trouvé</mark>
    {% endfor %}
    </div>
    
    <p>Il y a <strong>{{ nb_players }}</strong> joueurs enregistrés dans la base de données</p>

    <ul>
    {% for winner in winners %}
        <li>{{winner.nickname}}</li>
    {% endfor %}
    </ul>

{% endblock %}

{% block footer %}{% endblock %}